#!/bin/bash
pushd $(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd) >/dev/null

source ./SETMEUP
[[ HelloGraal.java -nt HelloGraal.class ]] && javac HelloGraal.java
[[ HelloGraal.class -nt hellograal ]] && native-image HelloGraal
./hellograal

popd >/dev/null
