#!/bin/bash
pushd $(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd) >/dev/null

output=$(wget -N https://github.com/graalvm/graalvm-ce-builds/releases/download/jdk-21.0.2/graalvm-community-jdk-21.0.2_linux-x64_bin.tar.gz 2>&1) || ( echo $output && exit 1 )

[[ "graalvm-community-jdk-21.0.2_linux-x64_bin.tar.gz" -nt "graalvm-community-openjdk-21.0.2+13.1" ]] && tar xvfm graalvm-community-jdk-21.0.2_linux-x64_bin.tar.gz

export JAVA_HOME=$(realpath graalvm-community-openjdk-21.0.2+13.1)
echo "$PATH" | grep -q "$JAVA_HOME/bin" || export PATH="$(realpath $JAVA_HOME)/bin:$PATH"

popd >/dev/null
